build:package:
    stage: build
    script:
        - pip install hatch
        - hatch build
    artifacts:
        paths:
            - dist/*

.run_test_pkg: &run_test_pkg
    dependencies:
      - build:package
    stage: tests
    before_script:
        - pip install hatch
    script:
        - hatch run test:${CI_PROJECT_DIR}/tests/${CI_JOB_NAME#*:}.py 2>&1 | tee output
        - if [[ ! -z $(grep "Warning\|warning" output) ]] ; then echo "Warnings in the output" ; exit 21 ; fi
    allow_failure:
        exit_codes: 21

tests_pkg:parameter_tests:
    <<: *run_test_pkg

tests_pkg:multiprocessing_tests:
    <<: *run_test_pkg

tests_pkg:pattern_tests:
    <<: *run_test_pkg

tests_pkg:benchmark_tests:
    <<: *run_test_pkg

tests_pkg:result_database_tests:
    <<: *run_test_pkg

tests_pkg:examples_tests:
    <<: *run_test_pkg

tests_pkg:yaml_tests:
    <<: *run_test_pkg

tests_pkg:xml_tests:
    <<: *run_test_pkg

tests_pkg:step_tests:
    <<: *run_test_pkg

tests_pkg:util_tests:
    <<: *run_test_pkg

tests_pkg:conf_tests:
    <<: *run_test_pkg

tests_pkg:substitute_tests:
    <<: *run_test_pkg
