# JUBE Benchmarking Environment
# Copyright (C) 2008-2024
# Forschungszentrum Juelich GmbH, Juelich Supercomputing Centre
# http://www.fz-juelich.de/jsc/jube
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For installation you can use:
#
# hatch build
# pip install dist/jube... --user
#
# to install it into your .local folder. .local/bin must be inside your $PATH.
# You can also change the folder by using --prefix instead of --user

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jube"
dynamic = [ "version" ]
description = "JUBE Benchmarking Environment"
readme = "README.md"
requires-python = ">=3.2"
license = "GPL-3.0-only"
authors = [
  { name = "Forschungszentrum Juelich GmbH", email = "jube.jsc@fz-juelich.de" },
]
dependencies = [
  "pyyaml",
  "ruamel.yaml",
  "matplotlib"
]
keywords = ['JUBE Benchmarking Environment']
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.2",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Benchmark",
    "Topic :: Software Development :: Testing"
]

[tool.hatch.version]
path = "jube/conf.py"
pattern = 'JUBE_VERSION = "(?P<version>[^"]+)"'

[tool.hatch.envs.test]
dependencies = [
"pytest",
"pytest-cov",
"matplotlib"
]

[project.scripts]
jube = "jube.main:main"

[project.urls]
Download = "https://www.fz-juelich.de/ias/jsc/jube"
Homepage = "https://www.fz-juelich.de/ias/jsc/jube"

[tool.hatch.build.targets.wheel.shared-data]
examples = "share/jube/examples"
"docs/JUBE.pdf" = "share/jube/docu/JUBE.pdf"
"contrib/schema" = "share/jube/contrib/schema"
platform = "share/jube/platform"
AUTHORS = "share/jube/AUTHORS"
"CITATION.cff" = "share/jube/CITATION.cff"
CODE_OF_CONDUCT = "share/jube/CODE_OF_CONDUCT"
LICENSE = "share/jube/LICENSE"
RELEASE_NOTES = "share/jube/RELEASE_NOTES"

[tool.hatch.build.targets.wheel]
include = [
  "/jube",
]

[tool.hatch.build.targets.wheel.shared-scripts]
"bin/jube-autorun" = "jube-autorun"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "Q"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F401"] # Allow unused imports as they are needed for test-detection
